Repository HYF-Connect/hyf-connect, pull requests merged in 2021-12, with the labels that each got.

#28 creating db and config files
  .env
  api/config.js
  api/db/db.js
  api/db/scripts/README.md
  package-lock.json
  package.json
Labels: database

#29 creating the user table
  api/db/scripts/create-db.js
  api/db/scripts/create-user.js
  api/db/scripts/sync.js
  api/models/user.js
  package-lock.json
  package.json
Labels: database

#38 06-creating db region table
  api/db/scripts/create-region.js
  api/db/scripts/sync.js
  api/models/region.js
  api/models/user.js
Labels: database, sequelize

#39 07 - create table language
  .gitignore
  api/db/README.md
  api/db/scripts/README.md
  api/db/scripts/create-language.js
  api/db/scripts/create-user.js
  api/db/scripts/sync.js
  api/models/README.md
  api/models/language.js
  api/models/user.js
  package-lock.json
  package.json
Labels: database, sequelize

#40 09 create skill table
  api/db/scripts/create-skill.js
  api/db/scripts/sync.js
  api/models/skill.js
  package.json
Labels: database, sequelize

#42 11 create type table
  api/db/scripts/create-type.js
  api/db/scripts/sync.js
  api/models/type.js
  api/models/user.js
Labels: database, sequelize

#43 12 create user type table
  api/db/scripts/create-user-type.js
  api/db/scripts/sync.js
  api/models/user-type.js
  api/models/user.js
Labels: database, sequelize

#45 13 create project table
  api/db/scripts/create-project.js
  api/db/scripts/create-region.js
  api/db/scripts/create-user-skill.js
  api/db/scripts/sync.js
  api/models/project.js
Labels: database, sequelize

#46 05 - created class table
  api/db/scripts/create-class.js
  api/db/scripts/sync.js
  api/models/class.js
  package.json
Labels: database, sequelize

#49 16 create project class table
  api/db/scripts/create-project-class.js
  api/models/project-class.js
  api/models/project.js
  api/models/user.js
Labels: database, sequelize

#61 Set up Database to Heroku
  .env
  .gitignore
  api/db/README.md
  api/db/scripts/README.md
  api/db/scripts/create-class.js
  api/db/scripts/create-db.js
  api/db/scripts/create-language.js
  api/db/scripts/create-nationality.js
  api/db/scripts/create-project-class.js
  api/db/scripts/create-project-skill.js
  api/db/scripts/create-project.js
  api/db/scripts/create-region.js
  api/db/scripts/create-skill.js
  api/db/scripts/create-type.js
  api/db/scripts/create-user-language.js
  api/db/scripts/create-user-project.js
  api/db/scripts/create-user-skill.js
  api/db/scripts/create-user-type.js
  api/db/scripts/create-user.js
  api/db/scripts/seeds.js
  api/db/scripts/sync.js
  api/models/README.md
  api/models/class.js
  api/models/language.js
  api/models/nationality.js
  api/models/project-class.js
  api/models/project-skill.js
  api/models/project.js
  api/models/region.js
  api/models/skill.js
  api/models/type.js
  api/models/user-language.js
  api/models/user-project.js
  api/models/user-skill.js
  api/models/user-type.js
  api/models/user.js
  client/public/README.md
  package-lock.json
  package.json
Labels: database, heroku

#63 creating pages folders in client
  client/components/footer/footer.html
  client/components/footer/footer.js
  client/components/header/header.html
  client/components/header/header.js
  client/pages/about-us/about-us.html
  client/pages/about-us/about-us.js
  client/pages/add-new-project/add-new-project.html
  client/pages/add-new-project/add-new-project.js
  client/pages/avatar-page/avatar-page.html
  client/pages/avatar-page/avatar-page.js
  client/pages/contact-us/contact-us.html
  client/pages/contact-us/contact-us.js
  client/pages/edit-user-profile/edit-user-profile.html
  client/pages/edit-user-profile/edit-user-profile.js
  client/pages/members/members.html
  client/pages/members/members.js
  client/pages/projects/projects.html
  client/pages/projects/projects.js
  client/pages/sign-in/sign-in.html
  client/pages/sign-in/sing-in.js
  client/pages/sign-up/sign-up.html
  client/pages/sign-up/sign-up.js
  client/pages/user-profile/user-profile.html
  client/pages/user-profile/user-profile.js
  client/pages/user-project/user-project.html
  client/pages/user-project/user-project.js
Labels: planning

#64 31 - user registration
  .DS_Store
  api/.DS_Store
  api/access.log
  api/business-logic/README.md
  api/business-logic/user.js
  api/config.js
  api/config/default.js
  api/config/development.js
  api/config/index.js
  api/config/production.js
  api/controllers/README.md
  api/controllers/user.js
  api/data-access/api-calls/README.md
  api/data-access/api-calls/calls.js
  api/index.js
  api/middleware/README.md
  api/middleware/validate-user.js
  api/routes/README.md
  api/routes/index.js
  api/routes/resource.js
  api/routes/user.js
  client/index.html
  client/src/.DS_Store
  client/src/data-access/api-calls/README.md
  client/styles/styles.css
  data/persistent.json
  dev-scripts/document/document-directory.js
  dev-scripts/document/index.js
  dev-scripts/document/visualize-directory.js
  package-lock.json
  package.json
  vite.config.js
Labels: server, sign-up

#69 reorganize pages folder into src folder
  client/components/header/header.html
  client/components/header/header.js
  client/src/components/footer.js
  client/src/components/header.js
  client/src/pages/about-us/about-us.html
  client/src/pages/about-us/about-us.js
  client/src/pages/about-us/main-section.js
  client/src/pages/add-new-project/add-new-project.html
  client/src/pages/add-new-project/add-new-project.js
  client/src/pages/add-new-project/main-section.js
  client/src/pages/avatar-page/avatar-page.html
  client/src/pages/avatar-page/avatar-page.js
  client/src/pages/contact-us/contact-us.html
  client/src/pages/contact-us/contact-us.js
  client/src/pages/contact-us/main-section.js
  client/src/pages/edit-user-profile/edit-user-profile.html
  client/src/pages/edit-user-profile/edit-user-profile.js
  client/src/pages/edit-user-profile/main-section.js
  client/src/pages/home-page/home.html
  client/src/pages/home-page/home.js
  client/src/pages/home-page/main-section.js
  client/src/pages/members/main-section.js
  client/src/pages/members/members.html
  client/src/pages/members/members.js
  client/src/pages/projects/main-section.js
  client/src/pages/projects/projects.html
  client/src/pages/projects/projects.js
  client/src/pages/sign-in/main-section.js
  client/src/pages/sign-in/sign-in.html
  client/src/pages/sign-in/sign-in.js
  client/src/pages/sign-up/main-section.js
  client/src/pages/sign-up/sign-up.html
  client/src/pages/sign-up/sign-up.js
  client/src/pages/user-profile/main-section.js
  client/src/pages/user-profile/user-profile.html
  client/src/pages/user-profile/user-profile.js
  client/src/pages/user-project/main-section.js
  client/src/pages/user-project/user-project.html
  client/src/pages/user-project/user-project.js
  client/src/presentation/README.md
  client/src/presentation/components/README.md
  client/src/presentation/handlers/README.md
  client/src/presentation/listeners/README.md
  client/src/utils/README.md
Labels: planning

#71 32 user to login
  api/access.log
  api/business-logic/login.js
  api/controllers/login.js
  api/middleware/authenticate.js
  api/middleware/validate-login.js
  api/routes/authentication-route.js
  api/routes/index.js
  api/routes/login.js
  api/utils/create-token.js
  api/utils/validate-token.js
  package-lock.json
Labels: server, log-in

#72 22 create sign up page
  api/access.log
  api/controllers/user.js
  api/data-access/api-calls/README.md
  api/middleware/validate-user.js
  api/routes/README.md
  api/routes/index.js
  api/routes/resource.js
  api/routes/user.js
  client/.DS_Store
  client/index.html
  client/pages/sign-up/form-section.js
  client/pages/sign-up/main-section.js
  client/pages/sign-up/sign-up.html
  client/pages/sign-up/sign-up.js
  client/src/data-access/README.md
  client/src/data-access/api-calls/calls.js
  client/src/data-access/state/README.md
  client/src/data-access/state/state.js
  client/styles/sign-up.css
Labels: css, html, javascript, sign-up

#79 37 connect join us button (homepage)
  client/pages/homepage/banner-section.js
  client/pages/homepage/homepage.js
  client/styles/styles.css
Labels: css, html, javascript, homepage

#88 38 - links in the nav-bar
  client/components/header-component.js
  client/pages/homepage/banner-section.js
Labels: html, javascript

#89 fixed the logo path
  client/components/header-component.js
Labels: html, javascript

#90 22 - create main section for sign up page
  client/pages/sign-up/form-section.js
  client/pages/sign-up/main-section.js
  client/pages/sign-up/sign-up.html
  client/pages/sign-up/sign-up.js
  client/styles/sign-up.css
  client/styles/styles.css
Labels: html, javascript

#81 21 create login page
  api/business-logic/login.js
  api/business-logic/user.js
  api/data-access/api-calls/calls.js
  api/routes/index.js
  api/routes/user.js
  api/utils/create-token.js
  client/components/header-component.js
  client/pages/login/form-section.js
  client/pages/login/login.html
  client/pages/login/login.js
  client/pages/login/main-section.js
  client/pages/members/main-section.js
  client/pages/sign-in/sign-in.js
  client/src/data-access/api-calls/calls.js
  client/styles/login.css
  client/styles/styles.css
  package-lock.json
  package.json
Labels: css, html, javascript

#92 adding sign out function and username into the header
  api/business-logic/login.js
  client/components/header-component.js
  client/pages/login/form-section.js
  client/styles/styles.css
Labels: html, javascript, homepage, log-in

#74 30 create footer component
  api/access.log
  client/assets/logo-facebook.svg
  client/assets/logo-github.svg
  client/assets/logo-instagram.svg
  client/components/footer-component.js
  client/pages/about-us/about-us.js
  client/pages/homepage/homepage.js
  client/styles/styles.css
  package-lock.json
Labels: javascript, footer
